import { NextResponse } from "next/server";
import { validatePairingCode, completeWorldPairing, cleanupExpiredPairingCodes } from "@/lib/foundry/pairing";
import { createAuditLog, createAuditContextFromRequest, extractRequestContext, type AuditContext } from "@/lib/audit";

export const runtime = 'nodejs';

/**
 * POST /api/foundry/pair/confirm
 * Confirm world pairing by submitting a pairing code from Foundry.
 * 
 * This is called by the Foundry module to complete the pairing process.
 * 
 * Request body:
 * - pairingCode: string (required) - The pairing code generated by Harkonians
 * - foundryWorldId: string (required) - The Foundry world ID
 * 
 * Returns:
 * - 200 OK with world info and worldSecret on success
 * - 400 Bad Request on missing fields
 * - 401 Unauthorized if pairing code is invalid/expired/used
 * - 409 Conflict if world is already paired
 */
export async function POST(request: Request) {
  try {
    let body: { pairingCode?: string; foundryWorldId?: string } = {};
    try {
      const bodyText = await request.text();
      if (bodyText) {
        body = JSON.parse(bodyText);
      }
    } catch {
      // Empty or invalid JSON body
    }
    const { pairingCode, foundryWorldId } = body;

    // Validate required fields
    if (!pairingCode || !foundryWorldId) {
      const response = NextResponse.json(
        { error: "pairingCode and foundryWorldId are required" },
        { status: 400 }
      );
      addCorsHeaders(response, request);
      return response;
    }

    // Validate the pairing code format
    const { isValidPairingCodeFormat } = await import("@/lib/crypto");
    if (!isValidPairingCodeFormat(pairingCode)) {
      const response = NextResponse.json(
        { error: "Invalid pairing code format" },
        { status: 400 }
      );
      addCorsHeaders(response, request);
      return response;
    }

    // Validate the pairing code
    const pairingData = await validatePairingCode(pairingCode);

    if (!pairingData) {
      // Log the failed attempt
      const context = createAuditContextFromRequest(request, {
        foundryWorldId,
        error: "Invalid, expired, or already used pairing code",
      });
      await createAuditLog(
        "system",
        "PAIR_WORLD_REJECTED",
        "World",
        foundryWorldId,
        context as AuditContext
      );

      const response = NextResponse.json(
        { error: "Invalid, expired, or already used pairing code" },
        { status: 401 }
      );
      addCorsHeaders(response, request);
      return response;
    }

    // Complete the world pairing
    const result = await completeWorldPairing(pairingCode, foundryWorldId);

    if (!result.success) {
      // Log the failed attempt
      const context = createAuditContextFromRequest(request, {
        foundryWorldId,
        error: result.error || "Unknown error",
      });
      await createAuditLog(
        pairingData.userId,
        "PAIR_WORLD_REJECTED",
        "World",
        foundryWorldId,
        context
      );

      const response = NextResponse.json(
        { error: result.error || "Failed to complete pairing" },
        { status: 400 }
      );
      addCorsHeaders(response, request);
      return response;
    }

    // Log the successful pairing
    const context = createAuditContextFromRequest(request, {
      foundryWorldId,
      worldId: result.world?.id,
    });
    await createAuditLog(
      pairingData.userId,
      "PAIR_WORLD_COMPLETED",
      "World",
      result.world?.id || foundryWorldId,
      context
    );

    // Clean up expired pairing codes
    await cleanupExpiredPairingCodes();

    // Return success with world info
    // Note: If this is a new pairing, we return the raw world secret
    // The Foundry module MUST store this securely
    const responseData: Record<string, unknown> = {
      success: true,
      world: result.world,
      message: "World successfully paired",
    };

    // Include the raw world secret if this is a new world
    if ("rawWorldSecret" in result) {
      responseData.worldSecret = result.rawWorldSecret;
    }

    const response = NextResponse.json(responseData, { status: 200 });
    addCorsHeaders(response, request);
    return response;
  } catch (error) {
    console.error("Confirm pairing error:", error);
    const response = NextResponse.json(
      { error: "An error occurred during pairing confirmation" },
      { status: 500 }
    );
    addCorsHeaders(response, request);
    return response;
  }
}

/**
 * Helper to add CORS headers to a response.
 */
function addCorsHeaders(response: NextResponse, request: Request): void {
  response.headers.set("Access-Control-Allow-Credentials", "true");
  response.headers.set("Access-Control-Allow-Origin", request.headers.get("origin") || "*");
  response.headers.set("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS");
  response.headers.set("Access-Control-Allow-Headers", "Content-Type, Authorization");
}

// Handle OPTIONS for CORS preflight
export async function OPTIONS(request: Request) {
  const response = new NextResponse(null, { status: 204 });
  addCorsHeaders(response, request);
  return response;
}
